category_tags = {
    "EDUCATIONAL": 1,
    "FUN": 2,
    "SCIENCE": 3,
    "COSMOLOGY": 4,
    "ASTROLOGY": 5,
    "ART": 6,
    "PSYCOLOGY": 8,
    "ENTERTAINMENT": 9,
    "MOVIE": 10,
    "CARTOON": 11,
    "TV SHOW": 12,
    "SPORTS": 13,
    "MEDICAL": 14,
    "MATH": 16,
    "SOCIAL MEDIA": 17,
    "TECHNOLOGY": 18,
    "INTERNET": 19,
    "GAMING": 20,
    "HEALTH": 21,
    "EXCERCISE": 22,
    "COMPUTER SCIENCE": 23,
    "NEWS": 24,
    "RELIGIOUS": 25,
    "KIDS": 26,
    "HORROR": 27,
}
